export const RECORDS_REPOSITORY = Symbol('RECORDS_REPOSITORY');
export const PLAYER_PROGRESSION_PORT = Symbol('PLAYER_PROGRESSION_PORT');
export const BOSS_BATTLE_PORT = Symbol('BOSS_BATTLE_PORT');
export const RECORDS_ACHIEVEMENTS_PORT = Symbol('RECORDS_ACHIEVEMENTS_PORT');
