export const REWARDS_REPOSITORY = Symbol('REWARDS_REPOSITORY');
export const REWARDS_STATS_PORT = Symbol('REWARDS_STATS_PORT');
export const REWARD_CLAIM_TRANSACTION_PORT = Symbol('REWARD_CLAIM_TRANSACTION_PORT');
export const REWARDS_EVENTS_PORT = Symbol('REWARDS_EVENTS_PORT');
