export const TASKS_REPOSITORY = Symbol('TASKS_REPOSITORY');
export const TASK_COMPLETION_TRANSACTION_PORT = Symbol('TASK_COMPLETION_TRANSACTION_PORT');
export const TASKS_ACHIEVEMENTS_PORT = Symbol('TASKS_ACHIEVEMENTS_PORT');
